### ISSUE TITLE
Pretty slow

### ISSUE THREAD

**Issue by theobouwman** [appintheair/react-native-looped-carousel#43] opened 2016-10-28 16:35 UTC
The carousel is slow

**Comment by phil-r** [comment] 2016-10-30 19:20
@theobouwman What exactly is slow? You can change the delay between page changes using `delay` property.

**Comment by phil-r** [comment] 2016-10-30 19:21
I'm closing this for now as it's not clear what the problem is.

**Closed by phil-r** 2016-10-30 19:21 UTC
